"""Improve Description API endpoint for the AI Intelligence Layer.

Provides the POST /improve-description endpoint that rewrites a job description
using a specified improvement mode (short_and_crisp, detailed_and_formal,
or marketing_oriented).
"""

import logging

from fastapi import APIRouter, Depends, status
from fastapi.responses import JSONResponse

from app.ai.circuit_breaker import CircuitBreaker
from app.ai.config import AIConfig
from app.ai.description_improver import DescriptionImprover
from app.ai.exceptions import LLMServiceUnavailableError
from app.ai.models import (
    ErrorResponse,
    ImproveDescriptionRequest,
    ImproveDescriptionResponse,
)
from app.ai.prompt_manager import PromptTemplateManager

logger = logging.getLogger(__name__)

router = APIRouter(tags=["description-improvement"])


def _get_config() -> AIConfig:
    """Provide AIConfig instance."""
    return AIConfig()


def _get_description_improver(
    config: AIConfig = Depends(_get_config),
) -> DescriptionImprover:
    """Dependency that provides a configured DescriptionImprover instance."""
    prompt_manager = PromptTemplateManager(templates_dir=config.PROMPT_TEMPLATES_DIR)
    circuit_breaker = CircuitBreaker()
    return DescriptionImprover(
        config=config,
        prompt_manager=prompt_manager,
        circuit_breaker=circuit_breaker,
    )


@router.post(
    "/improve-description",
    response_model=ImproveDescriptionResponse,
    status_code=status.HTTP_200_OK,
    summary="Improve a job description",
    description=(
        "Rewrites a raw job description using a specified improvement mode. "
        "Supported modes: short_and_crisp, detailed_and_formal, marketing_oriented."
    ),
    responses={
        400: {"model": ErrorResponse, "description": "Invalid input"},
        422: {"model": ErrorResponse, "description": "Invalid mode value"},
        503: {"model": ErrorResponse, "description": "LLM service unavailable"},
    },
)
async def improve_description(
    request: ImproveDescriptionRequest,
    improver: DescriptionImprover = Depends(_get_description_improver),
) -> ImproveDescriptionResponse:
    """Improve a job description using the specified mode.

    Accepts a raw job description text and an improvement mode, then returns
    the improved version generated by the LLM.

    Args:
        request: The improvement request containing description and mode.
        improver: Injected DescriptionImprover service.

    Returns:
        ImproveDescriptionResponse with the improved text and mode used.
    """
    try:
        improved = await improver.improve(request.description, request.mode)
        return ImproveDescriptionResponse(
            improved_description=improved,
            mode=request.mode,
        )
    except LLMServiceUnavailableError as exc:
        logger.error("LLM service unavailable during description improvement: %s", exc)
        return JSONResponse(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            content=ErrorResponse(
                error="llm_service_unavailable",
                message="LLM service is temporarily unavailable",
            ).model_dump(),
        )
